// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtD7y3yG9zmVVkZ7P0KVYOLoZkVxPo8Xs',
    appId: '1:1020283409245:web:91a7e63086fba074f4ceb4',
    messagingSenderId: '1020283409245',
    projectId: 'personalfinancetracker-b2339',
    authDomain: 'personalfinancetracker-b2339.firebaseapp.com',
    storageBucket: 'personalfinancetracker-b2339.appspot.com',
    measurementId: 'G-Y4S0T9JPP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATvzxsQtL5icOGcnTpsXiHL_5N2B_ofFQ',
    appId: '1:1020283409245:android:217ca5217c8c9d89f4ceb4',
    messagingSenderId: '1020283409245',
    projectId: 'personalfinancetracker-b2339',
    storageBucket: 'personalfinancetracker-b2339.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW7DKH9yAe_TBE6O8-Ge0ZL7xZG1686ow',
    appId: '1:1020283409245:ios:3c4c410c37cb05b5f4ceb4',
    messagingSenderId: '1020283409245',
    projectId: 'personalfinancetracker-b2339',
    storageBucket: 'personalfinancetracker-b2339.appspot.com',
    iosBundleId: 'com.example.personalFinanceTracker',
  );
}
